@startuml
            set namespaceSeparator .
        entity1.EntityModel *-- "1..*" entity1.Entity
class entity1.EntityModel  {
}


entity1.Entity *-- "1..*" entity1.Property
class entity1.Entity  {
ID name
}


class entity1.Property  {
ID name
ID type
}


class ID <<match>> {
}


class STRING <<match>> {
}


class BOOL <<match>> {
}


class INT <<match>> {
}


class FLOAT <<match>> {
}


class STRICTFLOAT <<match>> {
}


class NUMBER <<match>> {
}

NUMBER <|-- STRICTFLOAT
NUMBER <|-- INT

class BASETYPE <<match>> {
}

BASETYPE <|-- NUMBER
BASETYPE <|-- FLOAT
BASETYPE <|-- BOOL
BASETYPE <|-- ID
BASETYPE <|-- STRING

class OBJECT <<abstract>> {
}

OBJECT <|-- BASETYPE

@enduml
