@startuml
set namespaceSeparator .


class rhapsody.RhapsodyModel  {
  STRING header
}


class rhapsody.Object  {
  ID name
}


class rhapsody.Property  {
  ID name
}


class rhapsody.Value <<abstract>> {
}


class rhapsody.GUID  {
  STRING value
}


class ID <<match>> {
}


class STRING <<match>> {
}


class BOOL <<match>> {
}


class INT <<match>> {
}


class FLOAT <<match>> {
}


class STRICTFLOAT <<match>> {
}


class NUMBER <<match>> {
}


class BASETYPE <<match>> {
}


class OBJECT <<abstract>> {
}


rhapsody.RhapsodyModel *-- rhapsody.Object
rhapsody.Object *-- "1..*" rhapsody.Property
rhapsody.Property *-- "0..*" rhapsody.Value
rhapsody.Value <|-- rhapsody.GUID
rhapsody.Value <|-- rhapsody.Object
NUMBER <|-- STRICTFLOAT
NUMBER <|-- INT
BASETYPE <|-- NUMBER
BASETYPE <|-- FLOAT
BASETYPE <|-- BOOL
BASETYPE <|-- ID
BASETYPE <|-- STRING
OBJECT <|-- BASETYPE
@enduml
