@startuml
set namespaceSeparator .


class workflow.Workflow  {
  ID name
  STRING desc
}


class workflow.Task  {
  ID name
}


class workflow.Action  {
  ID name
}


class workflow.Comment <<match>> {
}


class ID <<match>> {
}


class STRING <<match>> {
}


class BOOL <<match>> {
}


class INT <<match>> {
}


class FLOAT <<match>> {
}


class STRICTFLOAT <<match>> {
}


class NUMBER <<match>> {
}


class BASETYPE <<match>> {
}


class OBJECT <<abstract>> {
}


workflow.Workflow o-- workflow.Task
workflow.Workflow *-- "0..*" workflow.Task
workflow.Workflow *-- "0..*" workflow.Action
workflow.Task o-- "0..*" workflow.Action
workflow.Task o-- "0..*" workflow.Action
workflow.Task o-- "1..*" workflow.Task
NUMBER <|-- STRICTFLOAT
NUMBER <|-- INT
BASETYPE <|-- NUMBER
BASETYPE <|-- FLOAT
BASETYPE <|-- BOOL
BASETYPE <|-- ID
BASETYPE <|-- STRING
OBJECT <|-- BASETYPE
@enduml
