@startuml
set namespaceSeparator .


class json.File <<abstract>> {
}


class json.Array  {
}


class json.Value <<abstract>> {
}


class json.Object  {
}


class json.Member  {
  STRING key
}


class ID <<match>> {
}


class STRING <<match>> {
}


class BOOL <<match>> {
}


class INT <<match>> {
}


class FLOAT <<match>> {
}


class STRICTFLOAT <<match>> {
}


class NUMBER <<match>> {
}


class BASETYPE <<match>> {
}


class OBJECT <<abstract>> {
}


json.File <|-- json.Array
json.File <|-- json.Object
json.Array *-- "0..*" json.Value
json.Value <|-- json.Object
json.Value <|-- json.Array
json.Object *-- "0..*" json.Member
json.Member *-- json.Value
NUMBER <|-- STRICTFLOAT
NUMBER <|-- INT
BASETYPE <|-- NUMBER
BASETYPE <|-- FLOAT
BASETYPE <|-- BOOL
BASETYPE <|-- ID
BASETYPE <|-- STRING
OBJECT <|-- BASETYPE
@enduml
