@startuml
            set namespaceSeparator .
        rhapsody.RhapsodyModel *-- rhapsody.Object
class rhapsody.RhapsodyModel  {
STRING header
}


rhapsody.Object *-- "1..*" rhapsody.Property
class rhapsody.Object  {
ID name
}


rhapsody.Property *-- "0..*" rhapsody.Value
class rhapsody.Property  {
ID name
}


class rhapsody.Value <<abstract>> {
}

rhapsody.Value <|-- rhapsody.GUID
rhapsody.Value <|-- rhapsody.Object

class rhapsody.GUID  {
STRING value
}


class ID <<match>> {
}


class STRING <<match>> {
}


class BOOL <<match>> {
}


class INT <<match>> {
}


class FLOAT <<match>> {
}


class STRICTFLOAT <<match>> {
}


class NUMBER <<match>> {
}

NUMBER <|-- STRICTFLOAT
NUMBER <|-- INT

class BASETYPE <<match>> {
}

BASETYPE <|-- NUMBER
BASETYPE <|-- FLOAT
BASETYPE <|-- BOOL
BASETYPE <|-- ID
BASETYPE <|-- STRING

class OBJECT <<abstract>> {
}

OBJECT <|-- BASETYPE

@enduml
