@startuml
set namespaceSeparator .


class task_specification.Model  {
}


class task_specification.Skill  {
  ID name
}


class task_specification.SkillType  {
  ID name
}


class task_specification.Property  {
  ID name
  BASETYPE value
}


class task_specification.Import  {
  STRING importURI
}


class ID <<match>> {
}


class STRING <<match>> {
}


class BOOL <<match>> {
}


class INT <<match>> {
}


class FLOAT <<match>> {
}


class STRICTFLOAT <<match>> {
}


class NUMBER <<match>> {
}


class BASETYPE <<match>> {
}


class OBJECT <<abstract>> {
}


task_specification.Model *-- "0..*" task_specification.Import
task_specification.Model *-- "1..*" task_specification.Skill
task_specification.Model *-- "1..*" task_specification.SkillType
task_specification.Skill o-- task_specification.SkillType
task_specification.Skill *-- "1..*" task_specification.Property
NUMBER <|-- STRICTFLOAT
NUMBER <|-- INT
BASETYPE <|-- NUMBER
BASETYPE <|-- FLOAT
BASETYPE <|-- BOOL
BASETYPE <|-- ID
BASETYPE <|-- STRING
OBJECT <|-- BASETYPE
@enduml
