@startuml
set namespaceSeparator .


class B.Model  {
}


class B.X  {
  ID name
}


class B.R <<abstract>> {
}


class B.R1  {
}


class ID <<match>> {
}


class STRING <<match>> {
}


class BOOL <<match>> {
}


class INT <<match>> {
}


class FLOAT <<match>> {
}


class STRICTFLOAT <<match>> {
}


class NUMBER <<match>> {
}


class BASETYPE <<match>> {
}


class OBJECT <<abstract>> {
}


class A.Model  {
}


class A.E  {
  ID name
}


class A.C <<abstract>> {
}


class A.C1  {
  ID name
}


class A.TXT  {
  STRING txt
}


B.Model *-- "1..*" B.X
B.X *-- "1..*" B.R
B.R <|-- B.R1
B.R <|-- A.C1
B.R1 o-- A.E
NUMBER <|-- STRICTFLOAT
NUMBER <|-- INT
BASETYPE <|-- NUMBER
BASETYPE <|-- FLOAT
BASETYPE <|-- BOOL
BASETYPE <|-- ID
BASETYPE <|-- STRING
OBJECT <|-- BASETYPE
A.Model *-- "1..*" A.E
A.E *-- "1..*" A.C
A.C <|-- A.C1
A.C1 *-- A.TXT
@enduml
