@startuml
set namespaceSeparator .


class first_diamond.First  {
}


class ID <<match>> {
}


class STRING <<match>> {
}


class BOOL <<match>> {
}


class INT <<match>> {
}


class FLOAT <<match>> {
}


class STRICTFLOAT <<match>> {
}


class NUMBER <<match>> {
}


class BASETYPE <<match>> {
}


class OBJECT <<abstract>> {
}


class diamond.second.Second  {
}


class diamond.third.Third  {
}


first_diamond.First *-- "1..*" diamond.second.Second
first_diamond.First *-- "1..*" diamond.third.Third
NUMBER <|-- STRICTFLOAT
NUMBER <|-- INT
BASETYPE <|-- NUMBER
BASETYPE <|-- FLOAT
BASETYPE <|-- BOOL
BASETYPE <|-- ID
BASETYPE <|-- STRING
OBJECT <|-- BASETYPE
diamond.second.Second *-- diamond.last.MyDiamondRule
diamond.third.Third *-- diamond.last.MyDiamondRule
@enduml
