@startuml
set namespaceSeparator .


class C.Model  {
}


class ID <<match>> {
}


class STRING <<match>> {
}


class BOOL <<match>> {
}


class INT <<match>> {
}


class FLOAT <<match>> {
}


class STRICTFLOAT <<match>> {
}


class NUMBER <<match>> {
}


class BASETYPE <<match>> {
}


class OBJECT <<abstract>> {
}


class Base.Cls  {
  ID name
}


class Base.Method  {
  ID name
}


class Base.Obj  {
  ID name
}


class Base.Call  {
  ID name
}


class Base.Import  {
  STRING importURI
}


class Base.Comment <<match>> {
}


C.Model *-- "1..*" Base.Import
C.Model *-- "1..*" Base.Cls
C.Model *-- "1..*" Base.Obj
C.Model *-- "1..*" Base.Call
NUMBER <|-- STRICTFLOAT
NUMBER <|-- INT
BASETYPE <|-- NUMBER
BASETYPE <|-- FLOAT
BASETYPE <|-- BOOL
BASETYPE <|-- ID
BASETYPE <|-- STRING
OBJECT <|-- BASETYPE
Base.Cls o-- "1..*" Base.Cls
Base.Cls *-- "1..*" Base.Method
Base.Obj o-- Base.Cls
Base.Call o-- Base.Obj
Base.Call o-- Base.Method
@enduml
