@startuml
set namespaceSeparator .


class Ingredient.Model  {
}


class ID <<match>> {
}


class STRING <<match>> {
}


class BOOL <<match>> {
}


class INT <<match>> {
}


class FLOAT <<match>> {
}


class STRICTFLOAT <<match>> {
}


class NUMBER <<match>> {
}


class BASETYPE <<match>> {
}


class OBJECT <<abstract>> {
}


class Base.Recipe  {
}


class Base.Ingredient  {
  POS_FLOAT count
}


class Base.IngredientType  {
  ID name
}


class Base.Unit  {
  POS_FLOAT weight
  ID name
}


class Base.POS_FLOAT <<match>> {
}


class Base.UINT <<match>> {
}


Ingredient.Model *-- "1..*" Base.IngredientType
NUMBER <|-- STRICTFLOAT
NUMBER <|-- INT
BASETYPE <|-- NUMBER
BASETYPE <|-- FLOAT
BASETYPE <|-- BOOL
BASETYPE <|-- ID
BASETYPE <|-- STRING
OBJECT <|-- BASETYPE
Base.Recipe *-- "1..*" Base.Ingredient
Base.Ingredient o-- Base.Unit
Base.Ingredient o-- Base.IngredientType
Base.IngredientType o-- Base.IngredientType
Base.IngredientType *-- "1..*" Base.Unit
@enduml
