@startuml
            set namespaceSeparator .
        second.Second *-- "1..*" relative.third.Third
class second.Second  {
}


class ID <<match>> {
}


class STRING <<match>> {
}


class BOOL <<match>> {
}


class INT <<match>> {
}


class FLOAT <<match>> {
}


class STRICTFLOAT <<match>> {
}


class NUMBER <<match>> {
}

NUMBER <|-- STRICTFLOAT
NUMBER <|-- INT

class BASETYPE <<match>> {
}

BASETYPE <|-- NUMBER
BASETYPE <|-- FLOAT
BASETYPE <|-- BOOL
BASETYPE <|-- ID
BASETYPE <|-- STRING

class OBJECT <<abstract>> {
}

OBJECT <|-- BASETYPE

class relative.third.Third  {
INT t
}


@enduml
