@startuml
set namespaceSeparator .


class Users.Model  {
}


class Users.User  {
  ID name
}


class Users.Import  {
  STRING importURI
}


class ID <<match>> {
}


class STRING <<match>> {
}


class BOOL <<match>> {
}


class INT <<match>> {
}


class FLOAT <<match>> {
}


class STRICTFLOAT <<match>> {
}


class NUMBER <<match>> {
}


class BASETYPE <<match>> {
}


class OBJECT <<abstract>> {
}


class Components.Model  {
}


class Components.Package  {
  ID name
}


class Components.Interface  {
  ID name
}


class Components.Component  {
  ID name
}


class Components.Slot <<abstract>> {
}


class Components.SlotIn  {
  ID name
}


class Components.SlotOut  {
  ID name
}


class Components.Instance  {
  ID name
}


class Components.Connection  {
}


class Components.FQN <<match>> {
}


class Components.Comment <<match>> {
}


Users.Model *-- "1..*" Users.Import
Users.Model *-- "1..*" Users.User
Users.User o-- Components.Instance
NUMBER <|-- STRICTFLOAT
NUMBER <|-- INT
BASETYPE <|-- NUMBER
BASETYPE <|-- FLOAT
BASETYPE <|-- BOOL
BASETYPE <|-- ID
BASETYPE <|-- STRING
OBJECT <|-- BASETYPE
Components.Model *-- "0..*" Components.Package
Components.Package *-- "1..*" Components.Component
Components.Package *-- "1..*" Components.Instance
Components.Package *-- "1..*" Components.Connection
Components.Package *-- "1..*" Components.Package
Components.Package *-- "1..*" Components.Interface
Components.Component o-- "1..*" Components.Component
Components.Component *-- "0..*" Components.Slot
Components.Slot <|-- Components.SlotIn
Components.Slot <|-- Components.SlotOut
Components.SlotIn o-- "1..*" Components.Interface
Components.SlotOut o-- "1..*" Components.Interface
Components.Instance o-- Components.Component
Components.Connection o-- Components.Instance
Components.Connection o-- Components.SlotOut
Components.Connection o-- Components.Instance
Components.Connection o-- Components.SlotIn
@enduml
