@startuml
set namespaceSeparator .


class Interface.Model  {
}


class Interface.Package  {
  ID name
}


class Interface.RawType  {
  ID name
}


class Interface.Interface  {
  ID name
}


class Interface.Attribute <<abstract>> {
}


class Interface.RawTypeAttribute  {
  ID name
}


class Interface.EmbeddedAttribute  {
  ID name
}


class Interface.FQN <<match>> {
}


class Interface.Import  {
  STRING importURI
}


class Interface.Comment <<match>> {
}


class ID <<match>> {
}


class STRING <<match>> {
}


class BOOL <<match>> {
}


class INT <<match>> {
}


class FLOAT <<match>> {
}


class STRICTFLOAT <<match>> {
}


class NUMBER <<match>> {
}


class BASETYPE <<match>> {
}


class OBJECT <<abstract>> {
}


Interface.Model *-- "0..*" Interface.Import
Interface.Model *-- "0..*" Interface.Package
Interface.Package *-- "1..*" Interface.Interface
Interface.Package *-- "1..*" Interface.Package
Interface.Package *-- "1..*" Interface.RawType
Interface.Interface *-- "0..*" Interface.Attribute
Interface.Attribute <|-- Interface.RawTypeAttribute
Interface.Attribute <|-- Interface.EmbeddedAttribute
Interface.RawTypeAttribute o-- Interface.RawType
Interface.EmbeddedAttribute o-- Interface.Interface
NUMBER <|-- STRICTFLOAT
NUMBER <|-- INT
BASETYPE <|-- NUMBER
BASETYPE <|-- FLOAT
BASETYPE <|-- BOOL
BASETYPE <|-- ID
BASETYPE <|-- STRING
OBJECT <|-- BASETYPE
@enduml
